### ISSUE TITLE
Crashes on iOS 12 Beta 1

### ISSUE THREAD

**Issue by CSADn** [majd/cercube-for-youtube#9]
Cercube crashes instantly when tapping the icon on iOS 12 Beta 1.
Any chance to update it?

Best regards.

**Comment by D3m3rion** [comment]
Can confirm this.
I believe it's getting updated once the public beta is out, or at latest once iOS 12 is released. :)

**Comment by CSADn** [comment]
It crashes also con iOS 12 Beta 2.

I hope update will be very soon.

**Comment by CSADn** [comment]
New version released recently v4.2.2.4 but still crashing on iOS Beta 2.

**Comment by CSADn** [comment]
After release of iOS 12.1 Beta 1, Cercube v4.2.2.5 side loaded works like a charm!
